production:
  adapter:  postgresql
  host:     <%= ENV['DATABASE_HOST'] %>
  encoding: unicode
  database: <%= ENV['DATABASE_DB'] %>
  pool:     5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  template: template0
